import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// export const dynamic = "force-static";
// export const fetchCache = "only-cache";
// ❗ parent: fully STATIC + only cached fetch allowed

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}

// npx json-server db.json --watch --port 4000

{
  /*

  ✔️ What makes this real-world advanced
    🔁 1. Multiple components → same data
      ProjectHeader
      TasksList
      TaskItem

  👉 all reuse same cached functions

    Result:

    DB PROJECT: pr1
    DB TASKS: pr1

  👉 only ONE call each

  ⚡ 2. Preloading removes waterfall

    Without preload:

    auth → project → tasks → render

    With preload:

    (project + tasks) + auth → render

    👉 parallel execution

    🧠 3. Deep deduplication

    Even inside loop:

    TaskItem → getCachedTasks(id)

   👉 still NO extra DB calls

🏗️ 4. Real SaaS pattern

  project page
  tasks list
  permission check

shared data across components

  ✔️ What you learned (strictly from your article)
✅ cache()
  dedupe across whole tree
  even nested components

✅ preload()
  start early
  remove waterfalls

✅ combination
  preload + cache = production pattern

  This is how real dashboards are built using only:

  cache()
  preload()
  */
}
