import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// export const dynamic = "force-static";
// export const fetchCache = "only-cache";
// ❗ parent: fully STATIC + only cached fetch allowed

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}

// npx json-server db.json --watch --port 4000

{
  /*

  ✅ Deduplication using cache()
  ✅ Preloading pattern


   🔁 1. Deduplication (MOST IMPORTANT)
    ->  getItem(id) called multiple times
    ->  BUT terminal logs:

    DB CALL: 1
    👉 Only ONE DB call per request

    ⚡ 2. Preloading

      preload(id)

    ->  starts DB fetch before UI waits
    ->  while checkIsAvailable() runs

    👉 improves performance (parallel work)

    🧠 Flow (what actually happens)

    ->  preload(id) → starts fetch
    ->  checkIsAvailable() runs (1s delay)
    ->  Item calls getItem(id)
    ->  Data is already ready or reused

    ✔️ Core concepts (from your article)

    ✅ cache()
    ->  deduplicates same function calls
    ->  per request lifecycle

    ✅ preload()
    ->  starts fetch early
    ->  avoids waterfall

    ⚠️ Important
    ->  works only in server components
    ->  not global cache (only request-level)

    This is exactly:

    ->  deduplication
    ->  preload pattern
      → fully practical, no extra abstraction.

  */
}
