import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const dynamic = "force-static";
// ❗ parent: fully static

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}

// npx json-server db.json --watch --port 4000

{
  /*
    ❌ Case 1: Parent vs Child conflict
      Parent → force-static
      Child → force-dynamic

    👉 ❌ not allowed
    ✅ Case 2: Match parent
      Parent → force-static
      Child → force-static

    👉 ✅ works
    ⚠️ Case 3: auto
      Parent → force-static
      Child → auto

    👉 ✅ works (inherits static behavior)
    ❌ Case 4: breaking static rules
      Page marked static
      but uses no-store

    👉 ❌ runtime error
    ✔️ Rule (from your article, now visual)

      force-static = strict → no dynamic allowed
      force-dynamic = always runtime → cannot mix with static parent
      auto = safe middle → adapts
      Static route + dynamic fetch = ❌ error

    This shows:
      dynamic route conflicts
      how static/dynamic propagate
      why Next.js throws errors
  */
}
